In [ ]:
import numpy as np
# create a 1D numpy array
temperatures_w1 = np.array([22.5,25.3,20.8,23.4,26.1,24.8,21.9])
print(temperatures_w1)

[22.5 25.3 20.8 23.4 26.1 24.8 21.9]

In [ ]:
# Shape
temperatures_w1.shape

(7,)

In [ ]:
# Data Type
temperatures_w1.dtype

dtype('float64')

In [ ]:
# Number of elements
temperatures_w1.size

7

In [ ]:
# Inspect the shape of the temperatures_w1
print(temperatures_w1.shape)

(7,)

In [ ]:
   # Array Operations
# Convert celsius to fahrenheit
temperatures_w1_fahrenheit = (temperatures_w1 * 9/5) + 32
print(temperatures_w1_fahrenheit)

[72.5  77.54 69.44 74.12 78.98 76.64 71.42]

In [ ]:
# Maximum
temperatures_w1.max()

np.float64(26.1)

In [ ]:
# Minimum
temperatures_w1.min()

np.float64(20.8)

In [ ]:
# Mean
temperatures_w1.mean()

np.float64(23.542857142857144)

In [ ]:
   # Array Slicing & Indexing
# Extract 1st 3 days
temperatures_w1[:3]

array([22.5, 25.3, 20.8])

In [ ]:
# Extract the last 2 days
temperatures_w1[-2:]

array([24.8, 21.9])

In [ ]:
# Extract the middle 3 days
temperatures_w1[2:5]

array([20.8, 23.4, 26.1])

In [ ]:
# Create a 2D array
temperatures = np.array([[22.5,25.3,20.8,23.4,26.1,24.8,21.9],
                        [19.2,22.5,21.3,24.0,23.5,22.8,20.1]])
print(temperatures)

[[22.5 25.3 20.8 23.4 26.1 24.8 21.9]
 [19.2 22.5 21.3 24.  23.5 22.8 20.1]]

In [ ]:
# Shape of the 2D array
temperatures.shape

(2, 7)

In [ ]:
# Data Type
temperatures.dtype

dtype('float64')

In [ ]:
# Total number of elements
temperatures.size

14

In [ ]:
# Extract the temperatures
temperatures[:,-2:]

array([[24.8, 21.9],
       [22.8, 20.1]])

In [ ]:
   # Pandas
import pandas as pd
# Create a pandas series
Marks = pd.Series([95,92,89,85,80],index = ["Rank1","Rank2","Rank3","Rank4","Rank5"])
print(marks)

Rank1    95
Rank2    92
Rank3    89
Rank4    85
Rank5    80
dtype: int64

In [ ]:
   # Indexing & Slicing
# 1st rank mark
Marks["Rank1"]

np.int64(95)

In [ ]:
# loc
Marks.loc["Rank1":"Rank3"]

Rank1    95
Rank2    92
Rank3    89
dtype: int64

In [ ]:
# iloc
marks.iloc[2]

np.int64(89)

In [ ]:
# Apply a boolean mask
Marks[Marks > 90]

Rank1    95
Rank2    92
dtype: int64

In [ ]:
   # Manipulating Series
# Modify the mark for rank1
Marks["Rank1"] = 100
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
Rank5     80
dtype: int64

In [ ]:
# Remove
Marks = Marks.drop("Rank5")
print(Marks)

Rank1    100
Rank2     92
Rank3     89
Rank4     85
dtype: int64

In [ ]:
# Cmpute the CGPA
Marks/10

Rank1    10.0
Rank2     9.2
Rank3     8.9
Rank4     8.5
dtype: float64

In [ ]:
   # Pandas DataFrame
# Create the transactions DataFrame
transactions = pd.DataFrame({"TransactionID":[101,102,103,104,105,106,107,108,109,110],
                             "ProductCategory":["Electronics","Clothing","Electronics","Furniture",
                                                "Clothing","Electronics","Furniture","Clothing","Furniture",
                                                "Electronics"],
                             "Region":["North","South","North","East","West","North","East","West","South","North"],
                             "Amount":[200,150,300,450,200,250,300,180,350,400]})
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
   # Data Exploration
# Head
transactions.head()

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     150
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200

In [ ]:
# Tail
transactions.tail()

   TransactionID ProductCategory Region  Amount
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
# Shape
transactions.shape

(10, 4)

In [ ]:
# Column names
transactions.columns

Index(['TransactionID', 'ProductCategory', 'Region', 'Amount'], dtype='object')

In [ ]:
# Data Type
transactions.dtypes

TransactionID       int64
ProductCategory    object
Region             object
Amount              int64
dtype: object

In [ ]:
# Display ProductCategory & Amount columns
transactions[["ProductCategory","Amount"]]

  ProductCategory  Amount
0     Electronics     200
1        Clothing     150
2     Electronics     300
3       Furniture     450
4        Clothing     200
5     Electronics     250
6       Furniture     300
7        Clothing     180
8       Furniture     350
9     Electronics     400

In [ ]:
# iloc
transactions.iloc[:,-3:]

  ProductCategory Region  Amount
0     Electronics  North     200
1        Clothing  South     150
2     Electronics  North     300
3       Furniture   East     450
4        Clothing   West     200
5     Electronics  North     250
6       Furniture   East     300
7        Clothing   West     180
8       Furniture  South     350
9     Electronics  North     400

In [ ]:
# Filter
transactions[(transactions["Region"]=="North")&(transactions["Amount"]>200)]

   TransactionID ProductCategory Region  Amount
2            103     Electronics  North     300
5            106     Electronics  North     250
9            110     Electronics  North     400

In [ ]:
# Count
transactions["ProductCategory"].value_counts()

ProductCategory
Electronics    4
Clothing       3
Furniture      3
Name: count, dtype: int64

In [ ]:
# Unique Value
transactions["Region"].unique()

array(['North', 'South', 'East', 'West'], dtype=object)

In [ ]:
# Mean
transactions.groupby("Region")["Amount"].mean()

Region
East     375.0
North    287.5
South    250.0
West     190.0
Name: Amount, dtype: float64

In [ ]:
   # Manipulating the DataFrame
# Modify Amt
transactions.loc[1,"Amount"] =165
print(transactions)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400

In [ ]:
# Discount
transactions["Discount"] = transactions["Amount"]*0.10
print(transactions)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
8            109       Furniture  South     350      35.0
9            110     Electronics  North     400      40.0

In [ ]:
# Remove
transactions.drop(transactions[transactions["TransactionID"]==109].index)

   TransactionID ProductCategory Region  Amount  Discount
0            101     Electronics  North     200      20.0
1            102        Clothing  South     165      16.5
2            103     Electronics  North     300      30.0
3            104       Furniture   East     450      45.0
4            105        Clothing   West     200      20.0
5            106     Electronics  North     250      25.0
6            107       Furniture   East     300      30.0
7            108        Clothing   West     180      18.0
9            110     Electronics  North     400      40.0

In [ ]:
# Delete
transactions.drop("Discount",axis=1)

   TransactionID ProductCategory Region  Amount
0            101     Electronics  North     200
1            102        Clothing  South     165
2            103     Electronics  North     300
3            104       Furniture   East     450
4            105        Clothing   West     200
5            106     Electronics  North     250
6            107       Furniture   East     300
7            108        Clothing   West     180
8            109       Furniture  South     350
9            110     Electronics  North     400